# Generated by Django 5.2.3 on 2025-06-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieinfo",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="movieinfo",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
